# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker:
    - image: circleci/node:8.11
  working_directory: ~/Express-Template-JMM

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: update-node_modules
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build project
          command: yarn build
      - persist_to_workspace:
          root: "."
          paths:
            - dist

  test:
      <<: *defaults

      steps:
        - checkout
        - attach_workspace:
            at: "."
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run:
            name: run tests
            command: yarn test

  deploy:
      <<: *defaults
      steps:
        - run: ssh -o StrictHostKeyChecking=no ubuntu@return0software.com "source /home/ubuntu/express-api/deploy.sh"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      branches:
        only:
          - master
          - /rc-.*/
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test